let firstName = "Khatai";
let lastName = "Huseynzade";
let country = "Azerbaijan";
let city = "Baku";
const gravity = 9.81;
const boilingPoint = 100;
const PI = 3.14;
let name = "Khatai",
  live = "Azerbaijan";
