let firstName = "Asabaneh";
let lastName = "Yetayeh";
let country = "Finland";
let city = "Helsinki";
const gravity = 9.81;
const boilingPoint = 100;
const PI = 3.14;
let name = "Asabaneh",
  live = "Finland";
